export const dummyMissions = [
  {
    id: "1",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-04-11T19:00:00Z",
    status: "Failed",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }, { id: 5, username: "Zaden Pax" }],
    attended: [{ id: 3, username: "Coff" }, { id: 5, username: "Zaden Pax" }]
  },
  {
    id: "2",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Mission Running",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-04-12T14:30:00Z",
    status: "Successful",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "3",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Mining",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-04-13T16:00:00Z",
    status: "Successful",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "4",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Community",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-04-14T20:00:00Z",
    status: "Failed",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "5",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Other",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-05-11T22:45:00Z",
    status: "Successful",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "6",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/cgxglo9uezw21.jpg",
    date: "2019-05-12T19:00:00Z",
    status: "Successful",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "7",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/lf5jv387m7x21.jpg",
    date: "2019-05-13T19:30:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "8",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.imgur.com/wMG7Gl6.gif",
    date: "2019-05-14T20:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "9",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/tavwye5bbfx21.png",
    date: "2019-05-15T20:30:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "10",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/yul7r5v0u8x21.png",
    date: "2019-05-16T21:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "11",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/f1djmhbu37x21.png",
    date: "2019-05-17T22:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "12",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/hfx3wnl5hjw21.png",
    date: "2019-05-20T19:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "13",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/cr61vn490uw21.png",
    date: "2019-05-21T23:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "14",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "https://i.redd.it/c0bossg1slw21.png",
    date: "2019-06-01T16:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  },
  {
    id: "15",
    name: "Stanton System exploration",
    description: "We are going to explore around Stanton system for fun.",
    discordURL: "https://discord.gg/9Xfmuw",
    videoURL: "",
    category: "Exploration",
    location: "Port Olisar",
    feature_image: "",
    date: "2019-06-11T23:00:00Z",
    status: "Active",
    briefing: "",
    debriefing: "",
    commander: { id: 1, username: "Rommel" },
    rsvpUsers: [{ id: 2, username: "Axor" }, { id: 3, username: "Coff" }, { id: 4, username: "Tar Garyen" }],
    attended: [{ id: 3, username: "Coff" }]
  }
];